language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- "./build/build_and_test.sh"

deploy:
  provider: "heroku"
    api_key:
      secure: "TdsD8+PnSri9yQV8P9enFrmgm0Fmk16wFkzTeE9pY2DH9Ba8kUNWQaRCUTtZLTqoQPgH3C8xwah0xkRcuI9mpDRjRw+PLlF9L58LBdzmNBRbCLV4IrCkXfbKCR75ntwZCqnxxpi6Nqb9eA+k2iU+bps6B+3MrRrRNipb4XuXes+cQe1hysa0inEPnj2gHjM5UljHRmaAir6xQumG+Zp85UCuvkrB0asVnthq/6i2eU9yTE+YCidOSj9PuUCAe5OvmhP0DPATFrWyAu3UmMPK/T3jx53D+nNbyxh4IvbD8HGiRsMBuk3Epu3lAhCVv+OwDQIhjwRn0BOd6AEJsyhj8OCatvjnuCfcgGTVRrR4GXBnKINcA0VdbEesATHEs56wlC93muKZksGURr9bMw1gnr9kO84z5R2XGXSKXVvijkV/SqUzr4Ee9g2CMmQYBVT8wrIkQEJRDq3sUKfx/t1yh9L/Wt/n7OP/6MdgvzANKcNQCVpmiM+2d85sqxXb08yzMqarTDl/9vaX7f+hSzX3at9xTDIuiFZ73//eNLspg9PozD2WcTaSa3fYPuB2uSNY3lQ40dYt30A4YufXHi478KgnAkG6HswIFSQ7VYylHDqxl+qjEB/lPu1Rc2ugNcY0mzOV/kDauKHEpH3yz1P0ohSZ7hkB/o5nsuzCK5e5Az8="
    app: "alwy-jdjobs-dev"
